[package]
name = "teamy"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-runtime = "0.14.0"
anyhow = "1.0.70"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "cache", "framework", "standard_framework", "utils"] }
shuttle-secrets = "0.14.0"
shuttle-serenity = "0.14.0"
tokio = "1.27.0"
tracing = "0.1.37"
rand = "0.8.5"
sys-info = "0.9.1"
regex = "1.8.1"
mongodb = "2.5.0"
bson = { version = "2.6.1", features = ["chrono-0_4"] }
chrono = "0.4.26"
serde = "1.0.163"
